# Generated by Django 6.0 on 2026-01-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineappointment', '0005_appointmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed'), ('refund', 'refund')], default='created', max_length=20, null=True),
        ),
    ]
