# Generated by Django 6.0 on 2026-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineappointment', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'online'), ('ofline', 'ofline')], default='online', max_length=10),
        ),
    ]
