# Generated by Django 6.0 on 2026-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineappointment', '0007_appointment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=10),
        ),
    ]
